/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package expendio;

/**
 *
 * @author arelm
 */
public class panelnicio extends javax.swing.JFrame {

    /**
     * Creates new form panelnicio
     */
    public panelnicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBarraOpciones = new javax.swing.JPanel();
        jPanelCompra = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanelVenta = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanelProductos = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanelClientes = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanelUsuarios = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanelProveedores = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelPestañaVentas = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTableVentas = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jTextCodigoV = new javax.swing.JTextField();
        jTextProdV = new javax.swing.JTextField();
        jTextCantV = new javax.swing.JTextField();
        jTextPrecioV = new javax.swing.JTextField();
        jTextTotalV = new javax.swing.JTextField();
        jTextStockV = new javax.swing.JTextField();
        btnGenerarV = new javax.swing.JButton();
        jLabel23 = new javax.swing.JLabel();
        cbxCliente = new javax.swing.JComboBox<>();
        jTextCuantoPagaV = new javax.swing.JTextField();
        jTextCambioVenta = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanelPestañaCompra = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jTextCodigoC = new javax.swing.JTextField();
        jTextProdC = new javax.swing.JTextField();
        jTextCantC = new javax.swing.JTextField();
        jTextPrecioC = new javax.swing.JTextField();
        jTextTotalC = new javax.swing.JTextField();
        btnGenerarC = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTableCompras = new javax.swing.JTable();
        jLabel34 = new javax.swing.JLabel();
        cbxProv = new javax.swing.JComboBox<>();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jPanel14 = new javax.swing.JPanel();
        jPanelprod = new javax.swing.JPanel();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jTextProductos1 = new javax.swing.JTextField();
        jTextNomProducto1 = new javax.swing.JTextField();
        btnGuardarProd1 = new javax.swing.JButton();
        btnAgregarProd1 = new javax.swing.JButton();
        btnModificarProd1 = new javax.swing.JButton();
        jPassPrecProducto1 = new javax.swing.JPasswordField();
        jLabel41 = new javax.swing.JLabel();
        jPassPrecVProducto = new javax.swing.JPasswordField();
        jTextProductosProv1 = new javax.swing.JTextField();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTableUser1 = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jPanelPestañaProveedores1 = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jTextBusqClien1 = new javax.swing.JTextField();
        jTextNomClien1 = new javax.swing.JTextField();
        jTextDirecClien1 = new javax.swing.JTextField();
        jTextTelClien1 = new javax.swing.JTextField();
        btnGuardarClien2 = new javax.swing.JButton();
        btnAgregarClien2 = new javax.swing.JButton();
        btnModificarClien2 = new javax.swing.JButton();
        jLabel46 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTableProv1 = new javax.swing.JTable();
        jPanelPestañaUsuarios = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jTextBusqUser = new javax.swing.JTextField();
        jTextUsuario = new javax.swing.JTextField();
        jTextNomUsuario = new javax.swing.JTextField();
        cbxCaja = new javax.swing.JComboBox<>();
        cbxRol = new javax.swing.JComboBox<>();
        jPassUser = new javax.swing.JPasswordField();
        btnGuardarUsu3 = new javax.swing.JButton();
        btnAgregarUser3 = new javax.swing.JButton();
        btnModificarUser3 = new javax.swing.JButton();
        jLabel47 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUser = new javax.swing.JTable();
        PaginadoUser = new javax.swing.JPanel();
        jPanelPestañaProv = new javax.swing.JPanel();
        jPanelPestañaProveedores = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextBusqProv = new javax.swing.JTextField();
        jTextRFC = new javax.swing.JTextField();
        jTextNomProv = new javax.swing.JTextField();
        jTextTelProv = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextDirProv = new javax.swing.JTextArea();
        btnGuardarProv4 = new javax.swing.JButton();
        btnAgregarProv4 = new javax.swing.JButton();
        btnModificarProv4 = new javax.swing.JButton();
        jLabel48 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableProv = new javax.swing.JTable();
        PaginadoProv = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelBarraOpciones.setBackground(new java.awt.Color(172, 215, 20));

        jPanelCompra.setBackground(new java.awt.Color(172, 215, 20));

        jLabel3.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/3nuevacompra.png"))); // NOI18N
        jLabel3.setText("Nueva Compra");

        javax.swing.GroupLayout jPanelCompraLayout = new javax.swing.GroupLayout(jPanelCompra);
        jPanelCompra.setLayout(jPanelCompraLayout);
        jPanelCompraLayout.setHorizontalGroup(
            jPanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanelCompraLayout.setVerticalGroup(
            jPanelCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCompraLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel3)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanelVenta.setBackground(new java.awt.Color(172, 215, 20));

        jLabel2.setBackground(new java.awt.Color(172, 215, 20));
        jLabel2.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2nuevaventa.png"))); // NOI18N
        jLabel2.setText("Nueva Venta");

        javax.swing.GroupLayout jPanelVentaLayout = new javax.swing.GroupLayout(jPanelVenta);
        jPanelVenta.setLayout(jPanelVentaLayout);
        jPanelVentaLayout.setHorizontalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelVentaLayout.setVerticalGroup(
            jPanelVentaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVentaLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProductos.setBackground(new java.awt.Color(172, 215, 20));

        jLabel4.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4productos.png"))); // NOI18N
        jLabel4.setText("Productos");

        javax.swing.GroupLayout jPanelProductosLayout = new javax.swing.GroupLayout(jPanelProductos);
        jPanelProductos.setLayout(jPanelProductosLayout);
        jPanelProductosLayout.setHorizontalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelProductosLayout.setVerticalGroup(
            jPanelProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelProductosLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel4)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelClientes.setBackground(new java.awt.Color(172, 215, 20));

        jLabel5.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5clientes.png"))); // NOI18N
        jLabel5.setText("Clientes");

        javax.swing.GroupLayout jPanelClientesLayout = new javax.swing.GroupLayout(jPanelClientes);
        jPanelClientes.setLayout(jPanelClientesLayout);
        jPanelClientesLayout.setHorizontalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelClientesLayout.setVerticalGroup(
            jPanelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelClientesLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanelUsuarios.setBackground(new java.awt.Color(172, 215, 20));

        jLabel6.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6usuarios.png"))); // NOI18N
        jLabel6.setText("Usuarios");

        javax.swing.GroupLayout jPanelUsuariosLayout = new javax.swing.GroupLayout(jPanelUsuarios);
        jPanelUsuarios.setLayout(jPanelUsuariosLayout);
        jPanelUsuariosLayout.setHorizontalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelUsuariosLayout.setVerticalGroup(
            jPanelUsuariosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelUsuariosLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanelProveedores.setBackground(new java.awt.Color(172, 215, 20));

        jLabel7.setFont(new java.awt.Font("Candara", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7alternativa proveedor.png"))); // NOI18N
        jLabel7.setText("Proveedores");

        javax.swing.GroupLayout jPanelProveedoresLayout = new javax.swing.GroupLayout(jPanelProveedores);
        jPanelProveedores.setLayout(jPanelProveedoresLayout);
        jPanelProveedoresLayout.setHorizontalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelProveedoresLayout.setVerticalGroup(
            jPanelProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelProveedoresLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout jPanelBarraOpcionesLayout = new javax.swing.GroupLayout(jPanelBarraOpciones);
        jPanelBarraOpciones.setLayout(jPanelBarraOpcionesLayout);
        jPanelBarraOpcionesLayout.setHorizontalGroup(
            jPanelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelVenta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelProductos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelClientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelUsuarios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelProveedores, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelBarraOpcionesLayout.setVerticalGroup(
            jPanelBarraOpcionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBarraOpcionesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelVenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanelProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanelProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
        );

        getContentPane().add(jPanelBarraOpciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 130, 200, 520));

        jPanel2.setBackground(new java.awt.Color(77, 165, 203));

        jLabel1.setFont(new java.awt.Font("Candara", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Punto de venta");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel1)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 130));

        jPanel3.setBackground(new java.awt.Color(77, 165, 203));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.2empleado.png"))); // NOI18N
        jButton1.setText("User");

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N

        jLabel45.setFont(new java.awt.Font("Candara", 1, 30)); // NOI18N
        jLabel45.setForeground(new java.awt.Color(255, 255, 255));
        jLabel45.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel45.setText("Expendio de vinos y licores “El Entronque”");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel44)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(54, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel45)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel44)))
                .addGap(36, 36, 36))
        );

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 1100, 130));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 200, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.setBackground(new java.awt.Color(172, 215, 20));
        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        jPanelPestañaVentas.setBackground(new java.awt.Color(139, 156, 226));
        jPanelPestañaVentas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTableVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane4.setViewportView(jTableVentas);
        if (jTableVentas.getColumnModel().getColumnCount() > 0) {
            jTableVentas.getColumnModel().getColumn(0).setHeaderValue("Id");
            jTableVentas.getColumnModel().getColumn(1).setHeaderValue("Descripción");
            jTableVentas.getColumnModel().getColumn(2).setHeaderValue("Cantidad");
            jTableVentas.getColumnModel().getColumn(3).setHeaderValue("Precio");
            jTableVentas.getColumnModel().getColumn(4).setHeaderValue("Total");
        }

        jPanelPestañaVentas.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1030, 280));

        jLabel17.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel17.setText("Código");
        jPanelPestañaVentas.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel18.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4productos.png"))); // NOI18N
        jLabel18.setText("Producto");
        jPanelPestañaVentas.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel19.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel19.setText("Cantidad");
        jPanelPestañaVentas.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));

        jLabel20.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel20.setText("Precio");
        jPanelPestañaVentas.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 40, -1, -1));

        jLabel21.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel21.setText("Total");
        jPanelPestañaVentas.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 40, -1, -1));

        jLabel22.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel22.setText("Stock");
        jPanelPestañaVentas.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, -1, -1));
        jPanelPestañaVentas.add(jTextCodigoV, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 90, -1));
        jPanelPestañaVentas.add(jTextProdV, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 90, -1));
        jPanelPestañaVentas.add(jTextCantV, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 80, -1));
        jPanelPestañaVentas.add(jTextPrecioV, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 80, -1));
        jPanelPestañaVentas.add(jTextTotalV, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 70, 100, -1));
        jPanelPestañaVentas.add(jTextStockV, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 70, 80, -1));

        btnGenerarV.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnGenerarV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/2.2nuevaventacaja.png"))); // NOI18N
        btnGenerarV.setText("Generar");
        jPanelPestañaVentas.add(btnGenerarV, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 50, -1, 40));

        jLabel23.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/5clientes.png"))); // NOI18N
        jLabel23.setText("Cliente");
        jPanelPestañaVentas.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jPanelPestañaVentas.add(cbxCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 440, 130, -1));
        jPanelPestañaVentas.add(jTextCuantoPagaV, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 90, -1));
        jPanelPestañaVentas.add(jTextCambioVenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 440, 110, -1));

        jLabel24.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinero.png"))); // NOI18N
        jLabel24.setText("Total:");
        jPanelPestañaVentas.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 420, -1, -1));

        jLabel25.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel25.setText("--------");
        jPanelPestañaVentas.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, -1));

        jLabel26.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 0, 51));
        jLabel26.setText("Cambio:");
        jPanelPestañaVentas.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 440, -1, -1));

        jLabel27.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel27.setText("Pagar con:");
        jPanelPestañaVentas.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 440, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresorapdf.png"))); // NOI18N
        jPanelPestañaVentas.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 420, -1, -1));

        jTabbedPane1.addTab("tab1", jPanelPestañaVentas);

        jPanelPestañaCompra.setBackground(new java.awt.Color(139, 156, 226));
        jPanelPestañaCompra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel28.setText("Código");
        jPanelPestañaCompra.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel29.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/4productos.png"))); // NOI18N
        jLabel29.setText("Producto");
        jPanelPestañaCompra.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 40, -1, -1));

        jLabel30.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel30.setText("Cantidad");
        jPanelPestañaCompra.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, -1, -1));

        jLabel31.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel31.setText("Precio");
        jPanelPestañaCompra.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 40, -1, -1));

        jLabel33.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel33.setText("Total");
        jPanelPestañaCompra.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));
        jPanelPestañaCompra.add(jTextCodigoC, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 100, -1));
        jPanelPestañaCompra.add(jTextProdC, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 70, 280, -1));
        jPanelPestañaCompra.add(jTextCantC, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 70, 80, -1));
        jPanelPestañaCompra.add(jTextPrecioC, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 70, 80, -1));
        jPanelPestañaCompra.add(jTextTotalC, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 70, 100, -1));

        btnGenerarC.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        btnGenerarC.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresorapdf.png"))); // NOI18N
        btnGenerarC.setText("Generar");
        jPanelPestañaCompra.add(btnGenerarC, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 50, -1, 40));

        jTableCompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Descripción", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane5.setViewportView(jTableCompras);

        jPanelPestañaCompra.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 1030, 280));

        jLabel34.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/7alternativa proveedor.png"))); // NOI18N
        jLabel34.setText("Proveedor");
        jPanelPestañaCompra.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 440, -1, -1));

        jPanelPestañaCompra.add(cbxProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 440, 130, -1));

        jLabel37.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dinero.png"))); // NOI18N
        jLabel37.setText("Total:");
        jPanelPestañaCompra.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 420, -1, -1));

        jLabel38.setFont(new java.awt.Font("Candara", 1, 18)); // NOI18N
        jLabel38.setText("--------");
        jPanelPestañaCompra.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 440, -1, -1));

        jTabbedPane1.addTab("tab2", jPanelPestañaCompra);

        jPanel14.setBackground(new java.awt.Color(139, 156, 226));
        jPanel14.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelprod.setBackground(new java.awt.Color(139, 156, 226));
        jPanelprod.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 0, 14))); // NOI18N

        jLabel32.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel32.setText("Código");

        jLabel35.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel35.setText("Nombre");

        jLabel36.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel36.setText("Precio Compra");

        jLabel39.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel39.setText("Proveedor");

        jTextProductos1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jTextNomProducto1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        btnGuardarProd1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnGuardarProd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardarProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProd1ActionPerformed(evt);
            }
        });

        btnAgregarProd1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnAgregarProd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnAgregarProd1.setToolTipText("");

        btnModificarProd1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnModificarProd1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.2alternativaadministrador.png"))); // NOI18N
        btnModificarProd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProd1ActionPerformed(evt);
            }
        });

        jLabel41.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel41.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel41.setText("Precio Venta");

        jTextProductosProv1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanelprodLayout = new javax.swing.GroupLayout(jPanelprod);
        jPanelprod.setLayout(jPanelprodLayout);
        jPanelprodLayout.setHorizontalGroup(
            jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprodLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelprodLayout.createSequentialGroup()
                        .addGroup(jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNomProducto1)
                            .addComponent(jTextProductos1)
                            .addGroup(jPanelprodLayout.createSequentialGroup()
                                .addGroup(jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelprodLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jPassPrecProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addGroup(jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanelprodLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jPassPrecVProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel41, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(17, 17, 17))
                            .addComponent(jTextProductosProv1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanelprodLayout.createSequentialGroup()
                                .addGroup(jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel32)
                                    .addComponent(jLabel35)
                                    .addComponent(jLabel39))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelprodLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnGuardarProd1)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarProd1)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarProd1)
                        .addGap(27, 27, 27))))
        );
        jPanelprodLayout.setVerticalGroup(
            jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelprodLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextProductos1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelprodLayout.createSequentialGroup()
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPassPrecProducto1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelprodLayout.createSequentialGroup()
                        .addComponent(jLabel41)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPassPrecVProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(17, 17, 17)
                .addComponent(jLabel39)
                .addGap(3, 3, 3)
                .addComponent(jTextProductosProv1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanelprodLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarProd1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34))
        );

        jPanel14.add(jPanelprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, 270, 380));
        jPanelprod.getAccessibleContext().setAccessibleName("Nuevo Producto");
        jPanelprod.getAccessibleContext().setAccessibleDescription("");
        jPanelprod.getAccessibleContext().setAccessibleParent(jPanelProductos);

        jTableUser1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jTableUser1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Productos", "Precio", "Cant", "Estado"
            }
        ));
        jScrollPane6.setViewportView(jTableUser1);

        jPanel14.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 70, 660, 370));

        jTabbedPane1.addTab("tab3", jPanel14);
        jPanel14.getAccessibleContext().setAccessibleName("");

        jPanel15.setBackground(new java.awt.Color(139, 156, 226));
        jPanel15.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPestañaProveedores1.setBackground(new java.awt.Color(139, 156, 226));
        jPanelPestañaProveedores1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 0, 14))); // NOI18N

        jLabel40.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel40.setText("Nombre");

        jLabel42.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel42.setText("Dirección");

        jLabel43.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel43.setText("Teléfono");

        jTextBusqClien1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jTextBusqClien1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBusqClien1ActionPerformed(evt);
            }
        });

        jTextNomClien1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jTextDirecClien1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jTextTelClien1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        btnGuardarClien2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnGuardarClien2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardarClien2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarClien2ActionPerformed(evt);
            }
        });

        btnAgregarClien2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnAgregarClien2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnAgregarClien2.setToolTipText("");

        btnModificarClien2.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnModificarClien2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.2alternativaadministrador.png"))); // NOI18N
        btnModificarClien2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarClien2ActionPerformed(evt);
            }
        });

        jLabel46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPestañaProveedores1Layout = new javax.swing.GroupLayout(jPanelPestañaProveedores1);
        jPanelPestañaProveedores1.setLayout(jPanelPestañaProveedores1Layout);
        jPanelPestañaProveedores1Layout.setHorizontalGroup(
            jPanelPestañaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPestañaProveedores1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(btnGuardarClien2)
                .addGap(18, 18, 18)
                .addComponent(btnAgregarClien2)
                .addGap(18, 18, 18)
                .addComponent(btnModificarClien2)
                .addGap(25, 25, 25))
            .addGroup(jPanelPestañaProveedores1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPestañaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextDirecClien1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelPestañaProveedores1Layout.createSequentialGroup()
                        .addGroup(jPanelPestañaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextNomClien1)
                            .addComponent(jTextBusqClien1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextTelClien1)
                            .addGroup(jPanelPestañaProveedores1Layout.createSequentialGroup()
                                .addGroup(jPanelPestañaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel43)
                                    .addComponent(jLabel40)
                                    .addComponent(jLabel42)
                                    .addComponent(jLabel46))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanelPestañaProveedores1Layout.setVerticalGroup(
            jPanelPestañaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPestañaProveedores1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel46)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextBusqClien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel40)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomClien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel43)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextTelClien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel42)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextDirecClien1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(jPanelPestañaProveedores1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarClien2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarClien2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarClien2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30))
        );

        jPanel15.add(jPanelPestañaProveedores1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 270, 360));

        jTableProv1.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jTableProv1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Nombre", "Teléfono", "Dirección", "Estado"
            }
        ));
        jScrollPane8.setViewportView(jTableProv1);

        jPanel15.add(jScrollPane8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 70, 660, 370));

        jTabbedPane1.addTab("tab4", jPanel15);

        jPanelPestañaUsuarios.setBackground(new java.awt.Color(139, 156, 226));
        jPanelPestañaUsuarios.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(139, 156, 226));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Usuario", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 0, 14))); // NOI18N

        jLabel8.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel8.setText("Usuario");

        jLabel9.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel9.setText("Nombre");

        jLabel10.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel10.setText("Contraseña");

        jLabel11.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel11.setText("Caja");

        jLabel12.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel12.setText("Rol");

        jTextBusqUser.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jTextBusqUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBusqUserActionPerformed(evt);
            }
        });

        jTextUsuario.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jTextNomUsuario.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        btnGuardarUsu3.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnGuardarUsu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardarUsu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarUsu3ActionPerformed(evt);
            }
        });

        btnAgregarUser3.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnAgregarUser3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnAgregarUser3.setToolTipText("");

        btnModificarUser3.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnModificarUser3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.2alternativaadministrador.png"))); // NOI18N
        btnModificarUser3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarUser3ActionPerformed(evt);
            }
        });

        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel12))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNomUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextUsuario, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBusqUser))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addContainerGap(179, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel11)
                            .addComponent(cbxCaja, 0, 75, Short.MAX_VALUE)
                            .addComponent(cbxRol, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPassUser)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnGuardarUsu3)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarUser3)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarUser3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel47)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel47)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextBusqUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPassUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addComponent(jLabel11)
                .addGap(4, 4, 4)
                .addComponent(cbxCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbxRol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarUsu3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarUser3, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        jPanelPestañaUsuarios.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 460));

        jTableUser.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jTableUser.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Usuario", "Nombre", "Caja", "Rol", "Estado"
            }
        ));
        jScrollPane1.setViewportView(jTableUser);
        if (jTableUser.getColumnModel().getColumnCount() > 0) {
            jTableUser.getColumnModel().getColumn(5).setHeaderValue("Estado");
        }

        jPanelPestañaUsuarios.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 660, 370));

        javax.swing.GroupLayout PaginadoUserLayout = new javax.swing.GroupLayout(PaginadoUser);
        PaginadoUser.setLayout(PaginadoUserLayout);
        PaginadoUserLayout.setHorizontalGroup(
            PaginadoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        PaginadoUserLayout.setVerticalGroup(
            PaginadoUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelPestañaUsuarios.add(PaginadoUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 660, 60));

        jTabbedPane1.addTab("tab5", jPanelPestañaUsuarios);

        jPanelPestañaProv.setBackground(new java.awt.Color(139, 156, 226));
        jPanelPestañaProv.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanelPestañaProveedores.setBackground(new java.awt.Color(139, 156, 226));
        jPanelPestañaProveedores.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nuevo Proveedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Candara", 0, 14))); // NOI18N

        jLabel13.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel13.setText("RFC");

        jLabel14.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel14.setText("Nombre");

        jLabel15.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel15.setText("Teléfono");

        jLabel16.setFont(new java.awt.Font("Candara", 0, 14)); // NOI18N
        jLabel16.setText("Dirección");

        jTextBusqProv.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jTextBusqProv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextBusqProvActionPerformed(evt);
            }
        });

        jTextRFC.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jTextNomProv.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jTextTelProv.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N

        jTextDirProv.setColumns(20);
        jTextDirProv.setRows(5);
        jScrollPane3.setViewportView(jTextDirProv);

        btnGuardarProv4.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnGuardarProv4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/guardar.png"))); // NOI18N
        btnGuardarProv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarProv4ActionPerformed(evt);
            }
        });

        btnAgregarProv4.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnAgregarProv4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/nuevo.png"))); // NOI18N
        btnAgregarProv4.setToolTipText("");

        btnModificarProv4.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        btnModificarProv4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/6.2alternativaadministrador.png"))); // NOI18N
        btnModificarProv4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarProv4ActionPerformed(evt);
            }
        });

        jLabel48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar.png"))); // NOI18N

        javax.swing.GroupLayout jPanelPestañaProveedoresLayout = new javax.swing.GroupLayout(jPanelPestañaProveedores);
        jPanelPestañaProveedores.setLayout(jPanelPestañaProveedoresLayout);
        jPanelPestañaProveedoresLayout.setHorizontalGroup(
            jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                        .addGroup(jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelPestañaProveedoresLayout.createSequentialGroup()
                        .addGroup(jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextNomProv, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextRFC, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextBusqProv))
                        .addContainerGap())
                    .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                        .addGroup(jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextTelProv)
                            .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(9, 9, 9))
                    .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                .addGroup(jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnGuardarProv4)
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregarProv4)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarProv4))
                    .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel48)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelPestañaProveedoresLayout.setVerticalGroup(
            jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelPestañaProveedoresLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel48)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextBusqProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextRFC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextNomProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextTelProv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel16)
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelPestañaProveedoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardarProv4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAgregarProv4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnModificarProv4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanelPestañaProv.add(jPanelPestañaProveedores, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 270, 450));

        jTableProv.setFont(new java.awt.Font("Candara", 0, 12)); // NOI18N
        jTableProv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "RFC", "Nombre", "Teléfono", "Dirección", "Estado"
            }
        ));
        jScrollPane2.setViewportView(jTableProv);
        if (jTableProv.getColumnModel().getColumnCount() > 0) {
            jTableProv.getColumnModel().getColumn(1).setHeaderValue("RFC");
        }

        jPanelPestañaProv.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 20, 660, 370));

        javax.swing.GroupLayout PaginadoProvLayout = new javax.swing.GroupLayout(PaginadoProv);
        PaginadoProv.setLayout(PaginadoProvLayout);
        PaginadoProvLayout.setHorizontalGroup(
            PaginadoProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );
        PaginadoProvLayout.setVerticalGroup(
            PaginadoProvLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        jPanelPestañaProv.add(PaginadoProv, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 410, 660, 60));

        jTabbedPane1.addTab("tab6", jPanelPestañaProv);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 1100, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextBusqProvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBusqProvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBusqProvActionPerformed

    private void btnGuardarProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarProd1ActionPerformed

    private void jTextBusqUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBusqUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBusqUserActionPerformed

    private void jTextBusqClien1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextBusqClien1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextBusqClien1ActionPerformed

    private void btnModificarProd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProd1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarProd1ActionPerformed

    private void btnGuardarClien2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarClien2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarClien2ActionPerformed

    private void btnModificarClien2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarClien2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarClien2ActionPerformed

    private void btnGuardarUsu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarUsu3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarUsu3ActionPerformed

    private void btnModificarUser3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarUser3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarUser3ActionPerformed

    private void btnGuardarProv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarProv4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGuardarProv4ActionPerformed

    private void btnModificarProv4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarProv4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnModificarProv4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(panelnicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(panelnicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(panelnicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(panelnicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new panelnicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PaginadoProv;
    private javax.swing.JPanel PaginadoUser;
    private javax.swing.JButton btnAgregarClien2;
    private javax.swing.JButton btnAgregarProd1;
    private javax.swing.JButton btnAgregarProv4;
    private javax.swing.JButton btnAgregarUser3;
    private javax.swing.JButton btnGenerarC;
    private javax.swing.JButton btnGenerarV;
    private javax.swing.JButton btnGuardarClien2;
    private javax.swing.JButton btnGuardarProd1;
    private javax.swing.JButton btnGuardarProv4;
    private javax.swing.JButton btnGuardarUsu3;
    private javax.swing.JButton btnModificarClien2;
    private javax.swing.JButton btnModificarProd1;
    private javax.swing.JButton btnModificarProv4;
    private javax.swing.JButton btnModificarUser3;
    private javax.swing.JComboBox<String> cbxCaja;
    private javax.swing.JComboBox<String> cbxCliente;
    private javax.swing.JComboBox<String> cbxProv;
    private javax.swing.JComboBox<String> cbxRol;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    public javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    public javax.swing.JLabel jLabel5;
    public javax.swing.JLabel jLabel6;
    public javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanelBarraOpciones;
    private javax.swing.JPanel jPanelClientes;
    private javax.swing.JPanel jPanelCompra;
    private javax.swing.JPanel jPanelPestañaCompra;
    private javax.swing.JPanel jPanelPestañaProv;
    private javax.swing.JPanel jPanelPestañaProveedores;
    private javax.swing.JPanel jPanelPestañaProveedores1;
    private javax.swing.JPanel jPanelPestañaUsuarios;
    private javax.swing.JPanel jPanelPestañaVentas;
    private javax.swing.JPanel jPanelProductos;
    private javax.swing.JPanel jPanelProveedores;
    private javax.swing.JPanel jPanelUsuarios;
    private javax.swing.JPanel jPanelVenta;
    private javax.swing.JPanel jPanelprod;
    private javax.swing.JPasswordField jPassPrecProducto1;
    private javax.swing.JPasswordField jPassPrecVProducto;
    private javax.swing.JPasswordField jPassUser;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTableCompras;
    private javax.swing.JTable jTableProv;
    private javax.swing.JTable jTableProv1;
    private javax.swing.JTable jTableUser;
    private javax.swing.JTable jTableUser1;
    private javax.swing.JTable jTableVentas;
    private javax.swing.JTextField jTextBusqClien1;
    private javax.swing.JTextField jTextBusqProv;
    private javax.swing.JTextField jTextBusqUser;
    private javax.swing.JTextField jTextCambioVenta;
    private javax.swing.JTextField jTextCantC;
    private javax.swing.JTextField jTextCantV;
    private javax.swing.JTextField jTextCodigoC;
    private javax.swing.JTextField jTextCodigoV;
    private javax.swing.JTextField jTextCuantoPagaV;
    private javax.swing.JTextArea jTextDirProv;
    private javax.swing.JTextField jTextDirecClien1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextNomClien1;
    private javax.swing.JTextField jTextNomProducto1;
    private javax.swing.JTextField jTextNomProv;
    private javax.swing.JTextField jTextNomUsuario;
    private javax.swing.JTextField jTextPrecioC;
    private javax.swing.JTextField jTextPrecioV;
    private javax.swing.JTextField jTextProdC;
    private javax.swing.JTextField jTextProdV;
    private javax.swing.JTextField jTextProductos1;
    private javax.swing.JTextField jTextProductosProv1;
    private javax.swing.JTextField jTextRFC;
    private javax.swing.JTextField jTextStockV;
    private javax.swing.JTextField jTextTelClien1;
    private javax.swing.JTextField jTextTelProv;
    private javax.swing.JTextField jTextTotalC;
    private javax.swing.JTextField jTextTotalV;
    private javax.swing.JTextField jTextUsuario;
    // End of variables declaration//GEN-END:variables
}
